# Generated by Django 3.0.7 on 2020-07-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informacion_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artefacto',
            table='Artefacto',
        ),
        migrations.AlterModelTable(
            name='objetivo',
            table='Objetivo',
        ),
        migrations.AlterModelTable(
            name='recurso',
            table='Recurso',
        ),
        migrations.AlterModelTable(
            name='requisito',
            table='Requisito',
        ),
        migrations.AlterModelTable(
            name='seguridad',
            table='Seguridad',
        ),
    ]
