# Generated by Django 3.0.7 on 2020-07-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion_proyecto', '0002_auto_20200703_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefacto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
