# Generated by Django 3.0.7 on 2020-07-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion_proyecto', '0003_auto_20200703_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='tipo',
            field=models.CharField(choices=[('1', 'Recursos Humanos'), ('2', 'Recursos físicos no depreciables'), ('3', 'Recursos físicos depreciables'), ('4', 'Recursos intangibles')], max_length=1),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='tipo_costo',
            field=models.CharField(choices=[('1', 'Costo Directos'), ('2', 'Costos Indirectos'), ('3', 'Costo Extraordinarios')], max_length=1),
        ),
    ]
