# Generated by Django 3.0.7 on 2020-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informacion_proyecto', '0004_auto_20200703_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='vida_util',
            field=models.IntegerField(null=True),
        ),
    ]
