# Generated by Django 3.0.7 on 2020-06-29 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0007_auto_20200628_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Riesgo',
            },
        ),
        migrations.CreateModel(
            name='RiesgoProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad', models.CharField(max_length=1)),
                ('plan_mitigacion', models.TextField(blank=True)),
                ('plan_contingencia', models.TextField(blank=True)),
                ('evolucion', models.TextField(blank=True)),
                ('probabilidad_ocurrencia', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('magnitud_riesgo', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('estimacion_riesgo', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('estado', models.CharField(max_length=1)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('riesgo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgo.Riesgo')),
            ],
            options={
                'db_table': 'RisgoProyecto',
                'unique_together': {('proyecto', 'riesgo')},
            },
        ),
    ]
