# Generated by Django 3.0.5 on 2020-04-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20200421_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
