# Generated by Django 3.0.5 on 2020-04-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20200424_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_superuser',
        ),
    ]
