# Generated by Django 3.0.5 on 2020-06-07 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
