# Generated by Django 3.0.7 on 2020-06-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('A', 'administrador'), ('D', 'director'), ('M', 'miembro')], max_length=1),
        ),
        migrations.DeleteModel(
            name='TipoUsuario',
        ),
    ]
