# Generated by Django 3.0.7 on 2020-06-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20200623_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('1', 'administrador'), ('2', 'director'), ('3', 'miembro')], max_length=1),
        ),
    ]
