# Generated by Django 3.0.5 on 2020-05-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('A', 'Agil'), ('H', 'Hibrido'), ('T', 'Tradicional')], max_length=1)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Proyecto',
            },
        ),
    ]
