# Generated by Django 3.0.7 on 2020-06-23 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0008_auto_20200623_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metodologia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('A', 'Agil'), ('H', 'Hibrido'), ('T', 'Tradicional')], max_length=1)),
                ('estado', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Metodologia',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('S', 'Servicio'), ('P', 'Producto')], max_length=1)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('metodologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Metodologia')),
            ],
            options={
                'db_table': 'Proyecto',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('M', 'Miembro'), ('L', 'Lider')], max_length=1)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario')),
            ],
            options={
                'db_table': 'Miembro',
            },
        ),
    ]
