# Generated by Django 3.0.7 on 2020-06-25 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20200623_1752'),
        ('proyecto', '0002_reunion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='miembro',
            unique_together={('proyecto', 'usuario')},
        ),
    ]
