# Generated by Django 3.0.7 on 2020-06-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20200625_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='alcance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tiempo',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
