# Generated by Django 3.0.7 on 2020-06-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20200628_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tiempo',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
