# Generated by Django 3.0.7 on 2020-06-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0006_reunion_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='hora',
            field=models.CharField(max_length=10),
        ),
    ]
