# Generated by Django 3.0.7 on 2020-06-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0007_auto_20200628_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
