# Generated by Django 3.0.7 on 2020-06-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0003_remove_proceso_metodologia'),
        ('proyecto', '0008_auto_20200630_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='metodologia',
            field=models.CharField(choices=[('1', 'Agil'), ('2', 'Hibrido'), ('3', 'Tradicional')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Metodologia',
        ),
    ]
