# Generated by Django 3.0.7 on 2020-06-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0005_auto_20200628_1508'),
        ('proceso', '0002_auto_20200626_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_finalizacion', models.DateField()),
                ('estado', models.CharField(max_length=1)),
                ('predecesor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.Actividad')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proceso.Proceso')),
            ],
            options={
                'db_table': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.DecimalField(decimal_places=3, max_digits=5)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.Actividad')),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Miembro')),
            ],
            options={
                'db_table': 'Asignacion',
                'unique_together': {('miembro', 'actividad')},
            },
        ),
    ]
