# Generated by Django 3.0.7 on 2020-06-28 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='predecesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='actividad.Actividad'),
        ),
    ]
