# Generated by Django 3.0.7 on 2020-06-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0002_auto_20200628_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='puntuacion',
            field=models.DecimalField(decimal_places=3, max_digits=5, null=True),
        ),
    ]
