# Generated by Django 3.0.7 on 2020-06-26 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyecto', '0003_auto_20200625_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('1', 'Inicio'), ('2', 'Diseño'), ('3', 'Elaboración'), ('4', 'ejecución'), ('5', 'Cierre')], max_length=1)),
                ('tipo', models.CharField(choices=[('G', 'Gerencial'), ('T', 'Tecnico'), ('A', 'Apoyo')], max_length=1)),
                ('estado', models.CharField(max_length=1)),
                ('metodologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Metodologia')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.Proyecto')),
            ],
        ),
    ]
