# Generated by Django 3.0.7 on 2020-06-26 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20200625_1556'),
        ('proceso', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proceso',
            unique_together={('nombre', 'proyecto')},
        ),
        migrations.AlterModelTable(
            name='proceso',
            table='Proceso',
        ),
    ]
