# Generated by Django 3.0.7 on 2020-06-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proceso', '0002_auto_20200626_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='metodologia',
        ),
    ]
